### ISSUE TITLE
make the config.yml invisible to github

### ISSUE THREAD

**Issue by alfski** [RyongBo/panorama-webservice#16]
We don't really want the "live" config appearing in github
- create a config-sample.yml
  just "cp config.yml config-sample.yml" to be used an example config file
- git add config-sample.yml
- in .gitignore add a line "config.yml" so it won't be pushed to github

**Comment by ShamanicProgramming** [comment]
Should I have the web service fall through to use config-sample.yml if it can't find config.yml?

**Comment by alfski** [comment]
nahh... have it break.

"Missing config.yml"
