### ISSUE TITLE
Pull out the config strings into a config file

### ISSUE THREAD

**Issue by alfski** [RyongBo/panorama-webservice#7]
Pull out USER, PW, DB from the mainline code into a config file.

That way a sample config-sample-settings can be added to the repo.
But the live settings might be "config.yml" which can be .gitignored.

I'm not fussed if the config is YAML, JSON or simple key:value.
Would be good if it could contain comments, so probably not JSON.

**Comment by ShamanicProgramming** [comment]
Using YAML for config is working fine. For ease of install right now I've included PyYAML in the repository.
